# Generated by Django 5.0.6 on 2026-04-14 05:39

import django.db.models.deletion
import django_ckeditor_5.fields
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Abonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=350, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=0,
                        help_text="Полезно для сортировки | чем больше число, тем дальше на странице",
                        verbose_name="Порядковый номер",
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Контент"
                    ),
                ),
                (
                    "count_months",
                    models.PositiveSmallIntegerField(
                        default=1, verbose_name="Количество месяцев"
                    ),
                ),
                (
                    "price",
                    models.PositiveSmallIntegerField(
                        blank=True,
                        help_text="Цена в рублях от ...",
                        null=True,
                        verbose_name="Цена",
                    ),
                ),
                (
                    "days_freezing",
                    models.PositiveSmallIntegerField(
                        default=0, verbose_name="Дни заморозки"
                    ),
                ),
            ],
            options={
                "verbose_name": "Абонемент",
                "verbose_name_plural": "Абонементы",
            },
        ),
        migrations.CreateModel(
            name="OrderAbonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "is_payed",
                    models.BooleanField(default=False, verbose_name="Оплачен"),
                ),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "abonement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_abonements",
                        to="abonements.abonement",
                        verbose_name="Абонемент",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="order_abonements",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Заказ абонемента",
                "verbose_name_plural": "Заказы абонементов",
            },
        ),
    ]
