# Generated by Django 5.1 on 2025-09-19 10:43

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Abonement',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        choices=[
                            ('basic', 'Базовый'),
                            ('vip', 'VIP'),
                            ('premium', 'Премиум'),
                        ],
                        default='basic',
                        max_length=100,
                        verbose_name='Название',
                    ),
                ),
                (
                    'description',
                    models.TextField(
                        blank=True, null=True, verbose_name='Описание'
                    ),
                ),
                (
                    'price',
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name='Цена'
                    ),
                ),
                (
                    'number_of_months',
                    models.SmallIntegerField(
                        verbose_name='Количество месяцев'
                    ),
                ),
                (
                    'is_popular',
                    models.BooleanField(
                        default=False, verbose_name='Популярный'
                    ),
                ),
                (
                    'sale',
                    models.BooleanField(default=False, verbose_name='Акция'),
                ),
                (
                    'freeze_days',
                    models.PositiveSmallIntegerField(
                        blank=True,
                        default=0,
                        null=True,
                        verbose_name='Заморозка дней',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
            ],
            options={
                'verbose_name': 'Абонемент',
                'verbose_name_plural': 'Абонементы',
                'ordering': ['price'],
            },
        ),
        migrations.CreateModel(
            name='FreezeAbonement',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('start', models.DateField(verbose_name='Начало заморозки')),
                ('end', models.DateField(verbose_name='Конец заморозки')),
            ],
            options={
                'verbose_name': 'Замороженный абонемент',
                'verbose_name_plural': 'Замороженные абонементы',
            },
        ),
        migrations.CreateModel(
            name='GymVisit',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'visit_start',
                    models.DateTimeField(
                        auto_now_add=True,
                        verbose_name='Дата и время начала визита',
                    ),
                ),
                (
                    'visit_end',
                    models.DateTimeField(
                        auto_now=True,
                        null=True,
                        verbose_name='Дата и время окончания визита',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Визит в фитнес-клуб',
                'verbose_name_plural': 'Визиты в фитнес-клуб',
                'ordering': ['-visit_start'],
            },
        ),
        migrations.CreateModel(
            name='OrderAbonement',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('start', models.DateField(verbose_name='Начало абонемента')),
                (
                    'end',
                    models.DateField(
                        blank=True, null=True, verbose_name='Конец абонемента'
                    ),
                ),
                (
                    'status',
                    models.BooleanField(default=False, verbose_name='Оплачен'),
                ),
                (
                    'active',
                    models.BooleanField(default=False, verbose_name='Активен'),
                ),
            ],
            options={
                'verbose_name': 'Забронированный абонемент',
                'verbose_name_plural': 'Забронированные абонементы',
            },
        ),
        migrations.CreateModel(
            name='AbonementService',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        choices=[
                            ('gym', 'Тренажерный зал'),
                            ('pool', 'Бассейн'),
                            ('yoga', 'Йога'),
                            ('spa', 'SPA'),
                            ('cosmetology', 'Косметология'),
                            ('cycle', 'Велотренажер'),
                            ('water aerobics', 'Водное аэробик'),
                            ('dancing', 'Танцы'),
                            ('group', 'Групповые занятия'),
                        ],
                        max_length=100,
                        verbose_name='Название',
                    ),
                ),
                (
                    'abonement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='services',
                        to='abonements.abonement',
                        verbose_name='Абонемент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга абонемента',
                'verbose_name_plural': 'Услуги абонементов',
            },
        ),
        migrations.CreateModel(
            name='Discount',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'percent',
                    models.PositiveSmallIntegerField(
                        verbose_name='Процент скидки'
                    ),
                ),
                (
                    'start_date',
                    models.DateTimeField(verbose_name='Начало действия'),
                ),
                (
                    'end_date',
                    models.DateTimeField(verbose_name='Конец действия'),
                ),
                (
                    'is_active',
                    models.BooleanField(default=True, verbose_name='Активна'),
                ),
                (
                    'abonement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='discounts',
                        to='abonements.abonement',
                        verbose_name='Абонемент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Скидка',
                'verbose_name_plural': 'Скидки',
            },
        ),
    ]
