# Generated by Django 5.1 on 2025-09-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('abonements', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='gymvisit',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='gym_visits',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Пользователь',
            ),
        ),
        migrations.AddField(
            model_name='orderabonement',
            name='abonement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='orders',
                to='abonements.abonement',
                verbose_name='Абонемент',
            ),
        ),
        migrations.AddField(
            model_name='orderabonement',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='abonements',
                to=settings.AUTH_USER_MODEL,
                verbose_name='Клиент',
            ),
        ),
        migrations.AddField(
            model_name='gymvisit',
            name='order_abonement',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='visits',
                to='abonements.orderabonement',
                verbose_name='Абонемент',
            ),
        ),
        migrations.AddField(
            model_name='freezeabonement',
            name='my_abonement',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name='freezes',
                to='abonements.orderabonement',
                verbose_name='Абонемент',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='abonementservice',
            unique_together={('abonement', 'title')},
        ),
    ]
