# Generated by Django 5.1 on 2025-06-20 16:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonements", "0002_discount"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonement",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярный"),
        ),
    ]
