# Generated by Django 5.1 on 2025-09-19 11:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonementservice',
            name='title',
            field=models.CharField(
                choices=[
                    ('gym', 'Тренажерный зал'),
                    ('pool', 'Бассейн'),
                    ('yoga', 'Йога'),
                    ('spa', 'SPA'),
                    ('cosmetology', 'Косметология'),
                    ('cycle', 'Велотренажеры'),
                    ('water aerobics', 'Водная аэробика'),
                    ('dancing', 'Танцы'),
                    ('group', 'Групповые занятия'),
                ],
                max_length=100,
                verbose_name='Название',
            ),
        ),
    ]
