# Generated by Django 5.0.6 on 2026-04-16 05:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonements", "0002_orderabonement_created_at_orderabonement_updated_at"),
    ]

    operations = [
        migrations.CreateModel(
            name="AbonementService",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=350, unique=True, verbose_name="Название"
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        blank=True,
                        max_length=255,
                        null=True,
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
            ],
            options={
                "verbose_name": "Услуга абонемента",
                "verbose_name_plural": "Услуги абонемента",
            },
        ),
        migrations.CreateModel(
            name="AbonementServiceAbonement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "abonement",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="services",
                        to="abonements.abonement",
                        verbose_name="Абонемент",
                    ),
                ),
                (
                    "service",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="abonements",
                        to="abonements.abonementservice",
                        verbose_name="Услуга",
                    ),
                ),
            ],
        ),
    ]
