# Generated by Django 5.1 on 2025-07-13 17:57

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0003_abonement_is_popular'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonement',
            name='freeze_days',
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name='Заморозка дней'
            ),
        ),
        migrations.AddField(
            model_name='abonement',
            name='sale',
            field=models.BooleanField(default=False, verbose_name='Акция'),
        ),
        migrations.CreateModel(
            name='FreezeAbonement',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ('start', models.DateField(verbose_name='Начало заморозки')),
                ('end', models.DateField(verbose_name='Конец заморозки')),
                (
                    'my_abonement',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='freezes',
                        to='abonements.orderabonement',
                        verbose_name='Абонемент',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Замороженный абонемент',
                'verbose_name_plural': 'Замороженные абонементы',
            },
        ),
    ]
