# Generated by Django 5.1 on 2025-09-19 22:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0003_alter_abonementservice_title'),
        ('gym', '0005_alter_service_avatar'),
    ]

    operations = [
        migrations.AddField(
            model_name='abonement',
            name='services',
            field=models.ManyToManyField(
                blank=True,
                related_name='abonements',
                to='gym.service',
                verbose_name='Услуги',
            ),
        ),
        migrations.DeleteModel(
            name='AbonementService',
        ),
    ]
