# Generated by Django 5.0.6 on 2026-04-16 05:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("abonements", "0003_abonementservice_abonementserviceabonement"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="abonementserviceabonement",
            options={
                "verbose_name": "Услуга абонемента",
                "verbose_name_plural": "Услуги абонемента",
            },
        ),
    ]
