# Generated by Django 5.1 on 2025-07-14 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        (
            'abonements',
            '0004_abonement_freeze_days_abonement_sale_freezeabonement',
        ),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='abonementservice',
            unique_together={('abonement', 'title')},
        ),
    ]
