# Generated by Django 5.0.6 on 2026-04-18 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonements", "0005_promotion"),
    ]

    operations = [
        migrations.AddField(
            model_name="abonement",
            name="is_popular",
            field=models.BooleanField(default=False, verbose_name="Популярный"),
        ),
    ]
