# Generated by Django 5.0.6 on 2026-04-23 05:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("contenttypes", "0002_remove_content_type_name"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Notification",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("booked_training", "Вы забронировали тренировку"),
                            ("paid_training", "Оплатили тренировку"),
                            ("booked_subscription", "Забронировали абонемент"),
                            ("paid_subscription", "Оплатили абонемент"),
                            ("training_canceled", "Тренировка отменена"),
                            ("comment_published", "Ваш комментарий опубликован"),
                            (
                                "comment_moderation",
                                "Ваш комментарий должен пройти модерацию",
                            ),
                            ("comment_rejected", "Ваш комментарий не был опубликован"),
                            (
                                "subscription_expiring",
                                "Ваш абонемент приближается к концу",
                            ),
                            ("training_reminder", "Приближается дата вашей тренировки"),
                            ("feedback_received", "Мы получили ваше обращение"),
                        ],
                        max_length=50,
                        verbose_name="Тип уведомления",
                    ),
                ),
                (
                    "object_id",
                    models.PositiveIntegerField(
                        blank=True, null=True, verbose_name="ID связанного объекта"
                    ),
                ),
                (
                    "message",
                    models.TextField(
                        blank=True, verbose_name="Дополнительный текст (если нужен)"
                    ),
                ),
                (
                    "is_read",
                    models.BooleanField(default=False, verbose_name="Прочитано"),
                ),
                (
                    "content_type",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="contenttypes.contenttype",
                        verbose_name="Тип связанного объекта",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="notifications",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Уведомление",
                "verbose_name_plural": "Уведомления",
                "ordering": ["-created_at"],
                "indexes": [
                    models.Index(
                        fields=["content_type", "object_id"],
                        name="notificatio_content_702c56_idx",
                    )
                ],
            },
        ),
    ]
