# Generated by Django 5.0.6 on 2026-04-23 05:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("notifications", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="notification",
            name="object_id",
            field=models.UUIDField(
                blank=True, null=True, verbose_name="ID связанного объекта"
            ),
        ),
    ]
