version: '3.8'

services:
  # PostgreSQL сервис
  db:
    image: postgres:13-alpine
    environment:
      POSTGRES_DB: ${DB_NAME:-mydb}
      POSTGRES_USER: ${DB_USER:-myuser}
      POSTGRES_PASSWORD: ${DB_PASSWORD:-mypassword}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER:-myuser}"]
      interval: 5s
      timeout: 5s
      retries: 5
    ports:
      - "5432:5432"

  # Django сервис
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    environment:
      DB_ENGINE: django.db.backends.postgresql
      DB_NAME: ${DB_NAME:-mydb}
      DB_USER: ${DB_USER:-myuser}
      DB_PASSWORD: ${DB_PASSWORD:-mypassword}
      DB_HOST: db
      DB_PORT: 5432
      DEBUG: ${DEBUG:-0}
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
    restart: unless-stopped

  # Nuxt3 сервис
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    environment:
      NUXT_PUBLIC_API_URL: http://backend:8000
    volumes:
      - ./frontend:/app
      - /app/node_modules
    ports:
      - "3000:3000"
    depends_on:
      - backend
    restart: unless-stopped

volumes:
  postgres_data: