[tool.black]
line-length = 88
target-version = ['py310', 'py311', 'py312']
skip-string-normalization = true 
include = '\.pyi?$'
exclude = '''
/(
    migrations
  | static
  | templates
  | \.venv
  | build
  | dist
)/
'''

[tool.isort]
profile = "black"
line_length = 88
multi_line_output = 3
include_trailing_comma = true
force_grid_wrap = 0
use_parentheses = true
ensure_newline_before_comments = true
skip = ["migrations", ".venv", "static"]

[tool.autoflake]
remove-all-unused-imports = true
remove-unused-variables = true
ignore-init-module-imports = true



#autoflake --in-place --remove-unused-variables --remove-all-unused-imports -r trainers/