# Generated by Django 5.1 on 2025-06-20 12:30

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Contact",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("phone", "Телефон"),
                            ("mail", "Почта"),
                            ("address", "Адрес"),
                            ("mode", "Режим работы"),
                            ("latitude", "Широта"),
                            ("longitude", "Долгота"),
                        ],
                        default="phone",
                        max_length=50,
                        verbose_name="Тип",
                    ),
                ),
                ("value", models.TextField(max_length=500, verbose_name="Значение")),
            ],
            options={
                "verbose_name": "Контакт",
                "verbose_name_plural": "Контакты",
            },
        ),
        migrations.CreateModel(
            name="Feedback",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("name", models.CharField(max_length=255, verbose_name="Имя")),
                ("phone", models.CharField(max_length=255, verbose_name="Телефон")),
                ("agree", models.BooleanField(default=False, verbose_name="Согласие")),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Проверен"),
                ),
            ],
            options={
                "verbose_name": "Обратная связь",
                "verbose_name_plural": "Обратная связь",
            },
        ),
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AlfaSms", max_length=100, verbose_name="Название сайта"
                    ),
                ),
                (
                    "copyright",
                    models.CharField(
                        default="© 2025 DVFitness. All rights reserved.",
                        max_length=255,
                        verbose_name="Копирайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Футер",
                "verbose_name_plural": "Футер",
            },
        ),
        migrations.CreateModel(
            name="FooterIcon",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("vk", "Вконтакте"),
                            ("tg", "Телеграм"),
                            ("whatsapp", "Ватсап"),
                            ("linkedin", "Linkedin"),
                        ],
                        max_length=255,
                        unique=True,
                        verbose_name="Название",
                    ),
                ),
                ("link", models.CharField(max_length=255, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Иконка в футере",
                "verbose_name_plural": "Иконки в футере",
            },
        ),
        migrations.CreateModel(
            name="FooterLink",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255, verbose_name="Заголовок")),
                ("link", models.CharField(max_length=255, verbose_name="Ссылка")),
            ],
            options={
                "verbose_name": "Ссылка в футере",
                "verbose_name_plural": "Ссылки в футере",
            },
        ),
    ]
