# Generated by Django 5.1 on 2025-09-19 10:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('name', models.CharField(max_length=255, verbose_name='Имя')),
                (
                    'phone',
                    models.CharField(max_length=255, verbose_name='Телефон'),
                ),
                (
                    'agree',
                    models.BooleanField(
                        default=False, verbose_name='Согласие'
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(
                        default=False, verbose_name='Проверен'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Обратная связь',
                'verbose_name_plural': 'Обратная связь',
            },
        ),
        migrations.CreateModel(
            name='Footer',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'site_name',
                    models.CharField(
                        default='AlfaSms',
                        max_length=100,
                        verbose_name='Название сайта',
                    ),
                ),
                (
                    'subtitle',
                    models.CharField(
                        default='AlfaSms',
                        max_length=100,
                        verbose_name='Подзаголовок',
                    ),
                ),
                (
                    'copyright',
                    models.CharField(
                        default='© 2025 ИП Соколов. Все права защищены.',
                        max_length=255,
                        verbose_name='Копирайт',
                    ),
                ),
                (
                    'developer_name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Разработчик',
                    ),
                ),
                (
                    'developer_link',
                    models.URLField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Ссылка на разработчика',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Футер',
                'verbose_name_plural': 'Футер',
            },
        ),
        migrations.CreateModel(
            name='Navigation',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(
                        max_length=255, unique=True, verbose_name='Ссылка'
                    ),
                ),
                (
                    'link',
                    models.CharField(
                        max_length=255, verbose_name='Значение ссылки'
                    ),
                ),
                (
                    'footer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='navigations',
                        to='contacts.footer',
                        verbose_name='Футер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Ссылка в футере',
                'verbose_name_plural': 'Ссылки в футере',
            },
        ),
        migrations.CreateModel(
            name='Contact',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('phone', 'Телефон'),
                            ('mail', 'Почта'),
                            ('tg', 'Telegram'),
                            ('whatsapp', 'WhatsApp'),
                            ('address', 'Адрес'),
                            ('mode', 'Режим работы'),
                            ('latitude', 'Широта'),
                            ('longitude', 'Долгота'),
                        ],
                        default='phone',
                        max_length=50,
                        unique=True,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'value',
                    models.CharField(max_length=500, verbose_name='Значение'),
                ),
                (
                    'footer',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name='contacts',
                        to='contacts.footer',
                        verbose_name='Футер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Контакт',
                'verbose_name_plural': 'Контакты',
                'unique_together': {('type', 'value')},
            },
        ),
    ]
