# Generated by Django 5.0.6 on 2026-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="social",
            name="type",
            field=models.CharField(
                choices=[
                    ("vk", "VK"),
                    ("tg", "TELEGRAM"),
                    ("max", "MAX"),
                    ("insta", "INSTAGRAM"),
                    ("youtube", "YOUTUBE"),
                    ("whatsapp", "WHATSAPP"),
                ],
                max_length=50,
                verbose_name="Тип контакта",
            ),
        ),
    ]
