# Generated by Django 5.1 on 2025-06-20 12:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="footericon",
            name="footer",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="icons",
                to="contacts.footer",
                verbose_name="Футер",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="footerlink",
            name="footer",
            field=models.ForeignKey(
                default="",
                on_delete=django.db.models.deletion.CASCADE,
                related_name="links",
                to="contacts.footer",
                verbose_name="Футер",
            ),
            preserve_default=False,
        ),
    ]
