# Generated by Django 5.0.6 on 2026-05-11 09:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_alter_social_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="vacancy",
            name="description",
            field=models.TextField(
                blank=True, max_length=2500, null=True, verbose_name="Описание"
            ),
        ),
    ]
