# Generated by Django 5.1 on 2025-06-01 11:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0002_remove_feedback_read_feedback_verified"),
    ]

    operations = [
        migrations.AddField(
            model_name="feedback",
            name="message",
            field=models.CharField(
                default="", max_length=1500, verbose_name="Сообщение"
            ),
            preserve_default=False,
        ),
    ]
