# Generated by Django 5.1 on 2025-06-24 15:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_faq"),
    ]

    operations = [
        migrations.DeleteModel(
            name="FAQ",
        ),
    ]
