# Generated by Django 5.1 on 2025-07-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'contacts',
            '0006_alter_feedback_created_at_alter_feedback_updated_at',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
    ]
