# Generated by Django 5.1 on 2025-05-18 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="read",
        ),
        migrations.AddField(
            model_name="feedback",
            name="verified",
            field=models.BooleanField(default=False, verbose_name="Проверен"),
        ),
    ]
