# Generated by Django 5.1 on 2025-06-01 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0003_feedback_message"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="feedback",
            name="message",
        ),
    ]
