# Generated by Django 5.1 on 2025-06-01 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0004_remove_feedback_message"),
    ]

    operations = [
        migrations.CreateModel(
            name="Footer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "site_name",
                    models.CharField(
                        default="AlfaSms", max_length=100, verbose_name="Название сайта"
                    ),
                ),
                (
                    "copyright",
                    models.CharField(
                        default="© 2023 AlfaSms. All rights reserved.",
                        max_length=255,
                        verbose_name="Копирайт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Футер",
                "verbose_name_plural": "Футер",
            },
        ),
    ]
