# Generated by Django 5.1 on 2025-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("contacts", "0005_footer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="footer",
            name="copyright",
            field=models.CharField(
                default="© 2025 DVFitness. All rights reserved.",
                max_length=255,
                verbose_name="Копирайт",
            ),
        ),
    ]
