# Generated by Django 5.1 on 2025-06-20 12:30

import common.upload_to
import common.validators
import django.core.validators
import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Trainer",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "content",
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name="Описание"
                    ),
                ),
                (
                    "position",
                    models.CharField(
                        choices=[
                            ("fitness", "Инструктор тренажерного зала"),
                            ("pool", "Инструктор бассейна"),
                            ("yoga", "Инструктор йоги"),
                        ],
                        max_length=100,
                        verbose_name="Должность",
                    ),
                ),
                ("first_name", models.CharField(max_length=100, verbose_name="Имя")),
                ("last_name", models.CharField(max_length=100, verbose_name="Фамилия")),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="Email"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        max_length=15,
                        unique=True,
                        validators=[common.validators.validate_russian_phone],
                        verbose_name="Телефон",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            common.validators.validate_image_extension_and_format
                        ],
                        verbose_name="Аватар",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренер",
                "verbose_name_plural": "Тренеры",
            },
        ),
        migrations.CreateModel(
            name="TrainerImage",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            common.validators.validate_image_extension_and_format
                        ],
                        verbose_name="Фото",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="images",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Фото тренера",
                "verbose_name_plural": "Фото тренеров",
            },
        ),
        migrations.CreateModel(
            name="TrainerRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        choices=[
                            ("basic", "Базовый"),
                            ("vip", "VIP"),
                            ("premium", "Премиум"),
                        ],
                        default="basic",
                        max_length=100,
                        verbose_name="Название тарифа",
                    ),
                ),
                (
                    "count_minutes",
                    models.SmallIntegerField(
                        choices=[(45, "45 минут"), (60, "60 минут"), (75, "75 минут")],
                        default=60,
                        verbose_name="Количество минут",
                    ),
                ),
                ("price", models.SmallIntegerField(default=1000, verbose_name="Цена")),
                (
                    "description",
                    models.TextField(blank=True, verbose_name="Описание тарифа"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="rates",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тариф тренера",
                "verbose_name_plural": "Тарифы тренеров",
                "ordering": ["-price"],
            },
        ),
        migrations.CreateModel(
            name="TrainerReviews",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "name",
                    models.CharField(
                        blank=True, max_length=100, null=True, verbose_name="Имя"
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        blank=True, max_length=254, null=True, verbose_name="Email"
                    ),
                ),
                (
                    "rating",
                    models.SmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name="Рейтинг",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name="Текст отзыва",
                    ),
                ),
                (
                    "verified",
                    models.BooleanField(default=False, verbose_name="Проверен"),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="reviews",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Отзыв о тренерах",
                "verbose_name_plural": "Отзывы о тренерах",
                "ordering": ["-created_at"],
            },
        ),
        migrations.CreateModel(
            name="TrainingSession",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("start", models.DateTimeField(verbose_name="Дата начала")),
                (
                    "end",
                    models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
                ),
                (
                    "is_booked",
                    models.BooleanField(default=False, verbose_name="Занято"),
                ),
                (
                    "client",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainings",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "rate",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainings",
                        to="trainers.trainerrate",
                        verbose_name="Тариф",
                    ),
                ),
                (
                    "trainer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="trainings",
                        to="trainers.trainer",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Забронированное занятие",
                "verbose_name_plural": "Забронированные занятия",
                "unique_together": {("trainer", "start", "end")},
            },
        ),
    ]
