# Generated by Django 5.1 on 2025-09-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='trainingsession',
            name='client',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainings',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='rate',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainings',
                to='trainers.trainerrate',
                verbose_name='Тариф',
            ),
        ),
        migrations.AddField(
            model_name='trainingsession',
            name='trainer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='trainings',
                to='trainers.trainer',
                verbose_name='Тренер',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='slot',
            unique_together={('trainer', 'date', 'start')},
        ),
        migrations.AlterUniqueTogether(
            name='trainerrate',
            unique_together={('trainer', 'title')},
        ),
        migrations.AlterUniqueTogether(
            name='trainersocialnetwork',
            unique_together={('trainer', 'type')},
        ),
        migrations.AlterUniqueTogether(
            name='trainingsession',
            unique_together={('trainer', 'start', 'end')},
        ),
    ]
