# Generated by Django 5.1 on 2025-06-23 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="TrainerSocialNetwork",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social_network",
                    models.CharField(
                        choices=[
                            ("vk", "VK"),
                            ("telegram", "Telegram"),
                            ("instagram", "Instagram"),
                            ("whatsapp", "WhatsApp"),
                        ],
                        max_length=100,
                        verbose_name="Социальная сеть",
                    ),
                ),
                ("link", models.URLField(verbose_name="Ссылка")),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="social_networks",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть тренера",
                "verbose_name_plural": "Социальные сети тренеров",
                "unique_together": {("trainer", "social_network")},
            },
        ),
    ]
