# Generated by Django 5.2.1 on 2025-05-16 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='trainingsession',
            options={'verbose_name': 'Забронированное занятие', 'verbose_name_plural': 'Забронированные занятия'},
        ),
    ]
