# Generated by Django 5.1 on 2025-09-20 10:17

import common.validators
import django.core.validators
import trainers.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='trainer',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=trainers.models.get_path_by_coach_avatar,
                validators=[
                    django.core.validators.FileExtensionValidator(
                        allowed_extensions=['jpg', 'jpeg', 'png', 'webp']
                    ),
                    common.validators.validate_image_size,
                ],
                verbose_name='Аватар',
            ),
        ),
    ]
