# Generated by Django 5.1 on 2025-05-17 09:36

import common.upload_to
import common.validators
import django.core.validators
import re
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0002_alter_trainingsession_options"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="avatar",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.upload_to.dynamic_upload_to,
                validators=[common.validators.validate_image_extension_and_format],
                verbose_name="Аватар",
            ),
        ),
        migrations.AlterField(
            model_name="trainer",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[
                    django.core.validators.RegexValidator(
                        message="Неправильный формат телефонного номера. Пример: +7 123 456 78 90 или 89123456789",
                        regex=re.compile("^\\+?7?\\d{10}$"),
                    )
                ],
                verbose_name="Телефон",
            ),
        ),
        migrations.AlterField(
            model_name="trainerimage",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.upload_to.dynamic_upload_to,
                validators=[common.validators.validate_image_extension_and_format],
                verbose_name="Фото",
            ),
        ),
    ]
