# Generated by Django 5.1 on 2025-06-23 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0003_trainerimage_alt"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="experience",
            field=models.PositiveSmallIntegerField(
                blank=True, default=0, null=True, verbose_name="Опыт работы"
            ),
        ),
    ]
