# Generated by Django 5.1 on 2025-06-01 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "trainers",
            "0006_alter_trainerimage_trainer_alter_trainerrate_trainer_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerrate",
            name="title",
            field=models.CharField(
                choices=[("basic", "Базовый"), ("vip", "VIP"), ("premium", "Премиум")],
                default="basic",
                max_length=100,
                verbose_name="Название тарифа",
            ),
        ),
    ]
