# Generated by Django 5.1 on 2025-06-24 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0007_alter_trainersocialnetwork_link"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainersocialnetwork",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="socials",
                to="trainers.trainer",
                verbose_name="тренер",
            ),
        ),
    ]
