# Generated by Django 5.1 on 2025-06-02 09:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0008_alter_trainerrate_count_minutes"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerreviews",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="reviews",
                to="trainers.trainer",
                verbose_name="тренер",
            ),
        ),
    ]
