# Generated by Django 5.1 on 2025-06-24 12:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0008_alter_trainersocialnetwork_trainer"),
    ]

    operations = [
        migrations.RenameField(
            model_name="trainersocialnetwork",
            old_name="social_network",
            new_name="type",
        ),
        migrations.AlterUniqueTogether(
            name="trainersocialnetwork",
            unique_together={("trainer", "type")},
        ),
    ]
