# Generated by Django 5.1 on 2025-06-24 13:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0009_rename_social_network_trainersocialnetwork_type_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="trainer",
            name="education",
            field=models.TextField(blank=True, null=True, verbose_name="Образование"),
        ),
        migrations.AlterField(
            model_name="trainersocialnetwork",
            name="type",
            field=models.CharField(
                choices=[
                    ("vk", "VK"),
                    ("tg", "Telegram"),
                    ("instagram", "Instagram"),
                    ("whatsapp", "WhatsApp"),
                ],
                max_length=100,
                verbose_name="Социальная сеть",
            ),
        ),
    ]
