# Generated by Django 5.1 on 2025-06-24 15:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0010_trainer_education_alter_trainersocialnetwork_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainersocialnetwork",
            name="type",
            field=models.CharField(
                choices=[
                    ("vk", "Вконтакте"),
                    ("telegram", "Телеграм"),
                    ("whatsapp", "Ватсап"),
                    ("linkedin", "Linkedin"),
                ],
                max_length=100,
                verbose_name="Социальная сеть",
            ),
        ),
    ]
