# Generated by Django 5.1 on 2025-06-26 16:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0011_alter_trainersocialnetwork_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="content",
            field=models.TextField(blank=True, null=True, verbose_name="Описание"),
        ),
    ]
