# Generated by Django 5.1 on 2025-07-09 07:37

import uuid

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0012_alter_trainer_content"),
    ]

    operations = [
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start", models.TimeField(verbose_name="Начало")),
                ("end", models.TimeField(verbose_name="Конец")),
                ("free", models.BooleanField(default=True, verbose_name="Свободен")),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот тренера",
                "verbose_name_plural": "Слоты тренера",
                "ordering": ["date", "start"],
            },
        ),
    ]
