# Generated by Django 5.1 on 2025-07-13 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0006_alter_post_slug"),
        ("trainers", "0015_trainer_services"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="services",
            field=models.ManyToManyField(
                blank=True, to="gym.service", verbose_name="Все услуги"
            ),
        ),
    ]
