# Generated by Django 5.1 on 2025-07-13 09:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0016_alter_trainer_services"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="trainerrate",
            unique_together={("trainer", "title")},
        ),
        migrations.CreateModel(
            name="Slot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                ("date", models.DateField(verbose_name="Дата")),
                ("start", models.TimeField(verbose_name="Начало")),
                ("end", models.TimeField(verbose_name="Конец")),
                ("free", models.BooleanField(default=True, verbose_name="Свободен")),
                (
                    "trainer",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="slots",
                        to="trainers.trainer",
                        verbose_name="тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Слот",
                "verbose_name_plural": "Слоты",
                "ordering": ["date", "start"],
                "unique_together": {("trainer", "date", "start")},
            },
        ),
    ]
