# Generated by Django 5.1 on 2025-07-13 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0017_alter_trainerrate_unique_together_slot'),
    ]

    operations = [
        migrations.RenameField(
            model_name='trainerreviews',
            old_name='name',
            new_name='first_name',
        ),
        migrations.AddField(
            model_name='trainerreviews',
            name='last_name',
            field=models.CharField(
                blank=True, max_length=100, null=True, verbose_name='Фамилия'
            ),
        ),
    ]
