# Generated by Django 5.1 on 2025-07-14 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trainers', '0018_rename_name_trainerreviews_first_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
        ),
        migrations.AlterField(
            model_name='trainerimage',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainerimage',
            name='updated_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
        ),
        migrations.AlterField(
            model_name='trainerreviews',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainerreviews',
            name='updated_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
        ),
    ]
