# Generated by Django 5.1 on 2025-07-14 21:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            'trainers',
            '0019_alter_slot_created_at_alter_slot_updated_at_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='slot',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='slot',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='trainerimage',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainerimage',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='trainerreviews',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainerreviews',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='trainingsession',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
    ]
