export const enum SocialIcons {
  GITHUB = "fa6-brands:github",
  LINKEDIN = "fa6-brands:linkedin",
  TELEGRAM = "fa6-brands:telegram",
  WHATSAPP = "fa6-brands:whatsapp",
  MAIL = "fa6-solid:envelope",
  PHONE = "fa6-solid:phone",
  VK = "fa6-brands:vk",
  GOOGLE = "fa6-brands:google",
  YANDDEX = "fa6-brands:yandex",
  USER = "fa6-solid:user",
  WORK = "fa6-solid:building",
  vk = "ri:vk-fill",
  tg = "ri:telegram-fill",
  whatsapp = "ri:whatsapp-fill",
  linkedin = "ri:linkedin-fill",
  github = "ri:github-fill",
  mail = "ri:mail-fill",
  phone = "ri:phone-fill",
}
