# Generated by Django 5.1 on 2025-07-14 13:06

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('legal', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(
                default=django.utils.timezone.now,
                verbose_name='Дата обновления',
            ),
        ),
    ]
