# Generated by Django 5.0.6 on 2026-04-13 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Полезно для сортировки | чем больше число, тем дальше на странице', verbose_name='Порядковый номер')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
                ('image', models.ImageField(blank=True, null=True, upload_to='categories/', verbose_name='Изображение')),
            ],
            options={
                'verbose_name': 'Категория',
                'verbose_name_plural': 'Категории',
            },
        ),
    ]
