# Generated by Django 5.1 on 2025-09-19 10:43

import common.mixins
import common.upload_to
import common.validators
import django.core.validators
import django_ckeditor_5.fields
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'icon',
                    models.FileField(
                        upload_to='advantages/icons/',
                        validators=[common.validators.validate_svg],
                        verbose_name='Иконка',
                    ),
                ),
                (
                    'alt',
                    models.CharField(
                        max_length=255, verbose_name='Описание к иконке'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
        migrations.CreateModel(
            name='Equipment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                (
                    'description',
                    models.TextField(max_length=1000, verbose_name='Описание'),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='equipment/',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'services',
                    models.TextField(
                        blank=True,
                        help_text='Через запятую',
                        max_length=255,
                        null=True,
                        verbose_name='услуги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Наши залы и оборудование',
                'verbose_name_plural': 'Наши залы и оборудование',
            },
            bases=(common.mixins.WebpImageMixin, models.Model),
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                ('question', models.TextField(verbose_name='Вопрос')),
                (
                    'answer',
                    models.TextField(
                        default='Здравствуйте',
                        help_text='Максимум 1000 символов',
                        verbose_name='Ответ',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Вопрос и ответ',
                'verbose_name_plural': 'Вопросы и ответы',
            },
        ),
        migrations.CreateModel(
            name='GymReviews',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'first_name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Имя',
                    ),
                ),
                (
                    'last_name',
                    models.CharField(
                        blank=True,
                        max_length=100,
                        null=True,
                        verbose_name='Фамилия',
                    ),
                ),
                (
                    'email',
                    models.EmailField(
                        blank=True,
                        max_length=254,
                        null=True,
                        verbose_name='Email',
                    ),
                ),
                (
                    'rating',
                    models.SmallIntegerField(
                        default=5,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(5),
                        ],
                        verbose_name='Рейтинг',
                    ),
                ),
                (
                    'text',
                    models.TextField(
                        blank=True,
                        max_length=5000,
                        null=True,
                        verbose_name='Текст отзыва',
                    ),
                ),
                (
                    'verified',
                    models.BooleanField(
                        default=False, verbose_name='Проверен'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Отзыв о тренажерном зале',
                'verbose_name_plural': 'Отзывы о тренажерном зале',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True,
                        max_length=200,
                        null=True,
                        unique=True,
                        verbose_name='URL',
                    ),
                ),
                (
                    'category',
                    models.CharField(
                        choices=[
                            ('workout', 'Тренировки'),
                            ('nutrition', 'Питание'),
                            ('news', 'Новости клуба'),
                            ('promo', 'Акции'),
                        ],
                        max_length=20,
                        verbose_name='Категория',
                    ),
                ),
                (
                    'image',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to='posts/previews/',
                        verbose_name='Изображение',
                    ),
                ),
                (
                    'is_published',
                    models.BooleanField(
                        default=True, verbose_name='Опубликовано'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Пост',
                'verbose_name_plural': 'Посты',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RecordOnSchedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Запись на групповое занятие',
                'verbose_name_plural': 'Записи на групповое занятие',
            },
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('date', models.DateField(verbose_name='Дата')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(verbose_name='Время окончания')),
                (
                    'max_participants',
                    models.PositiveSmallIntegerField(
                        default=10,
                        validators=[
                            django.core.validators.MinValueValidator(1),
                            django.core.validators.MaxValueValidator(20),
                        ],
                        verbose_name='Максимальное количество участников',
                    ),
                ),
                (
                    'current_participants',
                    models.PositiveSmallIntegerField(
                        default=0,
                        editable=False,
                        verbose_name='Текущее количество участников',
                    ),
                ),
                (
                    'status',
                    models.BooleanField(default=True, verbose_name='Активно'),
                ),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
                'ordering': ['date', 'start'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                (
                    'id',
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    'content',
                    django_ckeditor_5.fields.CKEditor5Field(
                        blank=True, verbose_name='Описание'
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'type',
                    models.CharField(
                        choices=[
                            ('gym', 'Тренажерный зал'),
                            ('pool', 'Бассейн'),
                            ('yoga', 'Йога'),
                            ('spa', 'SPA'),
                            ('cosmetology', 'Косметология'),
                            ('cycle', 'Велотренажер'),
                            ('water aerobics', 'Водное аэробик'),
                            ('dancing', 'Танцы'),
                            ('group', 'Групповые занятия'),
                        ],
                        default='gym',
                        max_length=100,
                        verbose_name='Тип',
                    ),
                ),
                (
                    'slug',
                    models.SlugField(
                        blank=True, max_length=255, null=True, unique=True
                    ),
                ),
                (
                    'avatar',
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to=common.upload_to.dynamic_upload_to,
                        validators=[
                            common.validators.validate_image_extension_and_format
                        ],
                        verbose_name='Фото',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
