# Generated by Django 5.1 on 2025-09-19 10:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('gym', '0001_initial'),
        ('trainers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='recordonschedule',
            name='user',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name='schedule',
            name='trainer',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name='schedules',
                to='trainers.trainer',
                verbose_name='Тренер',
            ),
        ),
        migrations.AddField(
            model_name='recordonschedule',
            name='schedule',
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to='gym.schedule'
            ),
        ),
        migrations.AddField(
            model_name='schedule',
            name='service',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to='gym.service',
                verbose_name='Услуга',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='recordonschedule',
            unique_together={('schedule', 'user')},
        ),
    ]
