# Generated by Django 5.1 on 2025-09-19 11:18

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='advantage',
            name='icon',
            field=models.FileField(
                blank=True,
                null=True,
                upload_to='advantages/icons/',
                validators=[common.validators.validate_svg],
                verbose_name='Иконка',
            ),
        ),
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(
                choices=[
                    ('gym', 'Тренажерный зал'),
                    ('pool', 'Бассейн'),
                    ('yoga', 'Йога'),
                    ('spa', 'SPA'),
                    ('cosmetology', 'Косметология'),
                    ('cycle', 'Велотренажеры'),
                    ('water aerobics', 'Водная аэробика'),
                    ('dancing', 'Танцы'),
                    ('group', 'Групповые занятия'),
                ],
                default='gym',
                max_length=100,
                verbose_name='Тип',
            ),
        ),
        migrations.AlterUniqueTogether(
            name='service',
            unique_together={('type',)},
        ),
    ]
