# Generated by Django 5.1 on 2025-06-24 15:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_faq"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="faq",
            options={
                "verbose_name": "Вопрос и ответ",
                "verbose_name_plural": "Вопросы и ответы",
            },
        ),
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(
                default="Здравствуйте",
                help_text="Максимум 1000 символов",
                max_length=1000,
                verbose_name="Ответ",
            ),
        ),
    ]
