# Generated by Django 5.1 on 2025-06-24 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_alter_faq_options_alter_faq_answer"),
    ]

    operations = [
        migrations.AlterField(
            model_name="faq",
            name="answer",
            field=models.TextField(
                default="Здравствуйте",
                help_text="Максимум 1000 символов",
                verbose_name="Ответ",
            ),
        ),
        migrations.AlterField(
            model_name="faq",
            name="question",
            field=models.TextField(verbose_name="Вопрос"),
        ),
    ]
