# Generated by Django 5.1 on 2025-09-19 11:31

import common.upload_to
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0003_alter_advantage_icon_alter_service_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=common.upload_to.dynamic_path_by_img,
                validators=[
                    common.validators.validate_image_extension_and_format
                ],
                verbose_name='Фото',
            ),
        ),
    ]
