# Generated by Django 5.1 on 2025-09-19 11:33

import common.validators
import gym.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0004_alter_service_avatar'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='avatar',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to=gym.models.path_by_service_img,
                validators=[
                    common.validators.validate_image_extension_and_format
                ],
                verbose_name='Фото',
            ),
        ),
    ]
