# Generated by Django 5.1 on 2025-06-26 16:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_post"),
    ]

    operations = [
        migrations.AlterField(
            model_name="post",
            name="slug",
            field=models.SlugField(
                blank=True, max_length=200, null=True, unique=True, verbose_name="URL"
            ),
        ),
    ]
