# Generated by Django 5.1 on 2025-07-14 12:59

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0007_rename_name_gymreviews_first_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Advantage',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                ('description', models.TextField(verbose_name='Описание')),
                (
                    'icon',
                    models.FileField(
                        upload_to='advantages/icons/',
                        validators=[common.validators.validate_svg],
                        verbose_name='Иконка',
                    ),
                ),
                (
                    'alt',
                    models.CharField(
                        max_length=255, verbose_name='Описание к иконке'
                    ),
                ),
            ],
            options={
                'verbose_name': 'Преимущество',
                'verbose_name_plural': 'Преимущества',
            },
        ),
    ]
