# Generated by Django 5.1 on 2025-07-14 21:33

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0009_advantage_created_at_advantage_updated_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'title',
                    models.CharField(max_length=255, verbose_name='Заголовок'),
                ),
                (
                    'description',
                    models.TextField(max_length=1000, verbose_name='Описание'),
                ),
                (
                    'image',
                    models.ImageField(
                        upload_to='equipment/', verbose_name='Изображение'
                    ),
                ),
                (
                    'services',
                    models.TextField(
                        blank=True,
                        help_text='Через запятую',
                        max_length=255,
                        null=True,
                        verbose_name='услуги',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Наши залы и оборудование',
                'verbose_name_plural': 'Наши залы и оборудование',
            },
            bases=(common.mixins.WebpImageMixin, models.Model),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='advantage',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='gymreviews',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='gymreviews',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='created_at',
            field=models.DateTimeField(
                auto_now_add=True, verbose_name='Дата создания'
            ),
        ),
        migrations.AlterField(
            model_name='post',
            name='updated_at',
            field=models.DateTimeField(
                auto_now=True, verbose_name='Дата обновления'
            ),
        ),
    ]
