# Generated by Django 5.1 on 2025-07-14 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0010_equipment_alter_advantage_created_at_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='image',
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to='equipment/',
                verbose_name='Изображение',
            ),
        ),
    ]
