# Generated by Django 5.1 on 2025-07-18 22:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0011_alter_equipment_image'),
        (
            'trainers',
            '0020_alter_slot_created_at_alter_slot_updated_at_and_more',
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='type',
            field=models.CharField(
                choices=[
                    ('gym', 'Тренажерный зал'),
                    ('pool', 'Бассейн'),
                    ('yoga', 'Йога'),
                    ('spa', 'SPA'),
                    ('cosmetology', 'Косметология'),
                    ('cycle', 'Велотренажер'),
                    ('water aerobics', 'Водное аэробик'),
                    ('dancing', 'Танцы'),
                    ('group', 'Групповые занятия'),
                ],
                default='gym',
                max_length=100,
                verbose_name='Тип',
            ),
        ),
        migrations.CreateModel(
            name='Schedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                ('date', models.DateField(verbose_name='Дата')),
                ('start', models.TimeField(verbose_name='Время начала')),
                ('end', models.TimeField(verbose_name='Время окончания')),
                (
                    'status',
                    models.BooleanField(default=True, verbose_name='Статус'),
                ),
                (
                    'service',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to='gym.service',
                        verbose_name='Услуга',
                    ),
                ),
                (
                    'trainer',
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name='schedules',
                        to='trainers.trainer',
                        verbose_name='Тренер',
                    ),
                ),
            ],
            options={
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
    ]
