# Generated by Django 5.1 on 2025-07-18 22:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0012_alter_service_type_schedule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='schedule',
            name='status',
            field=models.BooleanField(default=True, verbose_name='Активно'),
        ),
    ]
