# Generated by Django 5.1 on 2025-07-18 22:42

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gym', '0013_alter_schedule_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='schedule',
            options={
                'ordering': ['date', 'start'],
                'verbose_name': 'Расписание',
                'verbose_name_plural': 'Расписание',
            },
        ),
        migrations.AddField(
            model_name='schedule',
            name='current_participants',
            field=models.PositiveSmallIntegerField(
                default=0,
                editable=False,
                verbose_name='Текущее количество участников',
            ),
        ),
        migrations.AddField(
            model_name='schedule',
            name='max_participants',
            field=models.PositiveSmallIntegerField(
                default=10,
                validators=[
                    django.core.validators.MinValueValidator(1),
                    django.core.validators.MaxValueValidator(20),
                ],
                verbose_name='Максимальное количество участников',
            ),
        ),
        migrations.CreateModel(
            name='RecordOnSchedule',
            fields=[
                (
                    'id',
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name='ID',
                    ),
                ),
                (
                    'created_at',
                    models.DateTimeField(
                        auto_now_add=True, verbose_name='Дата создания'
                    ),
                ),
                (
                    'updated_at',
                    models.DateTimeField(
                        auto_now=True, verbose_name='Дата обновления'
                    ),
                ),
                (
                    'schedule',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to='gym.schedule',
                    ),
                ),
                (
                    'user',
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
            options={
                'verbose_name': 'Запись на групповое занятие',
                'verbose_name_plural': 'Записи на групповое занятие',
                'unique_together': {('schedule', 'user')},
            },
        ),
    ]
