# Generated by Django 5.2.1 on 2025-05-16 22:41

import django.core.validators
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='GymReviews',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('name', models.CharField(blank=True, max_length=100, null=True, verbose_name='Имя')),
                ('email', models.EmailField(blank=True, max_length=254, null=True, verbose_name='Email')),
                ('rating', models.SmallIntegerField(default=5, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(5)], verbose_name='Рейтинг')),
                ('text', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Текст отзыва')),
            ],
            options={
                'verbose_name': 'Отзыв о тренажерном зале',
                'verbose_name_plural': 'Отзывы о тренажерном зале',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок')),
                ('type', models.CharField(choices=[('gym', 'Безлимитные визиты'), ('unlimited_visits', 'Безлимитные визиты'), ('pool', 'Бассейн'), ('yoga', 'Йога'), ('spa', 'SPA'), ('cosmetology', 'Косметология'), ('cycle', 'Велотренажер'), ('water aerobics', 'Водное аэробик'), ('dancing', 'Танцы')], default='gym', max_length=100, verbose_name='Тип')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Услуга',
                'verbose_name_plural': 'Услуги',
            },
        ),
    ]
