# Generated by Django 5.1 on 2025-05-17 12:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_gymreviews_verified"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="service",
            name="title",
        ),
        migrations.AlterField(
            model_name="service",
            name="type",
            field=models.CharField(
                choices=[
                    ("gym", "Тренажерный зал"),
                    ("pool", "Бассейн"),
                    ("yoga", "Йога"),
                    ("spa", "SPA"),
                    ("cosmetology", "Косметология"),
                    ("cycle", "Велотренажер"),
                    ("water aerobics", "Водное аэробик"),
                    ("dancing", "Танцы"),
                ],
                default="gym",
                max_length=100,
                verbose_name="Тип",
            ),
        ),
    ]
