# Generated by Django 5.0.6 on 2026-04-13 05:45

import seo.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="RobotsTXT",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "text",
                    models.TextField(
                        default=" User-agent: *\n                    Disallow: /admin/\n                    Disallow: /api/\n                    Sitemap: https://yourdomain.com/sitemap.xml\n                    ",
                        help_text="Текст файла robots.txt, который будет отдавать сервер.",
                        verbose_name="Текст файла robots.txt",
                    ),
                ),
            ],
            options={
                "verbose_name": "robots.txt",
                "verbose_name_plural": "robots.txt",
            },
        ),
        migrations.CreateModel(
            name="SEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL путь, например: about/ (без начального и конечного слэша)",
                        max_length=255,
                        unique=True,
                        verbose_name="URL путь",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True,
                        help_text="Макс. 60 символов",
                        max_length=255,
                        verbose_name="Заголовок (title)",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True,
                        help_text="Макс. 160 символов",
                        verbose_name="Описание (meta description)",
                    ),
                ),
                (
                    "keywords",
                    models.TextField(
                        blank=True,
                        help_text="Через запятую",
                        null=True,
                        verbose_name="Ключевые слова (meta keywords)",
                    ),
                ),
                (
                    "canonical_url",
                    models.URLField(
                        blank=True,
                        help_text="Полный URL для canonical ссылки",
                        null=True,
                        verbose_name="Canonical URL",
                    ),
                ),
                (
                    "noindex",
                    models.BooleanField(
                        default=False,
                        help_text="Запретить индексацию страницы",
                        verbose_name="Noindex",
                    ),
                ),
                (
                    "nofollow",
                    models.BooleanField(
                        default=False,
                        help_text="Запретить переход по ссылкам на странице",
                        verbose_name="Nofollow",
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="OG Заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="OG Описание"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[seo.models.validate_image_extension],
                        verbose_name="OG Изображение",
                    ),
                ),
                (
                    "og_type",
                    models.CharField(
                        choices=[
                            (
                                "website",
                                "Website — общая веб-страница (главная, контакты, о салоне)",
                            ),
                            (
                                "product",
                                "Product — товар (подарочный сертификат, косметика для дома, набор ухода)",
                            ),
                            (
                                "service",
                                "Service — услуга салона (стрижка, окрашивание, маникюр, педикюр, косметология, массаж)",
                            ),
                            (
                                "blog",
                                "Blog — блог, полезные статьи, бьюти-советы, тренды",
                            ),
                            (
                                "article",
                                "Article — статья или новость (альтернатива для блога)",
                            ),
                            (
                                "profile",
                                "Profile — профиль мастера (стилист, косметолог, бровист)",
                            ),
                            ("place", "Place — место (салон красоты, филиал, студия)"),
                            (
                                "event",
                                "Event — событие (мастер-класс, день красоты, акция, вебинар)",
                            ),
                        ],
                        default="website",
                        help_text="Тип Open Graph: website, article, product...",
                        max_length=50,
                        verbose_name="OG Тип",
                    ),
                ),
                (
                    "og_site_name",
                    models.CharField(
                        blank=True,
                        help_text="Название сайта для Open Graph",
                        max_length=255,
                        null=True,
                        verbose_name="OG Site Name",
                    ),
                ),
                (
                    "priority",
                    models.DecimalField(
                        decimal_places=1,
                        default=0.5,
                        help_text="От 0.1 до 1.0",
                        max_digits=2,
                        verbose_name="Приоритет в sitemap",
                    ),
                ),
                (
                    "changefreq",
                    models.CharField(
                        choices=[
                            ("always", "Всегда"),
                            ("hourly", "Каждый час"),
                            ("daily", "Ежедневно"),
                            ("weekly", "Еженедельно"),
                            ("monthly", "Ежемесячно"),
                            ("yearly", "Ежегодно"),
                            ("never", "Никогда"),
                        ],
                        default="weekly",
                        max_length=10,
                        verbose_name="Частота изменений",
                    ),
                ),
                (
                    "lastmod",
                    models.DateTimeField(
                        auto_now=True, verbose_name="Дата последнего изменения"
                    ),
                ),
                (
                    "json_ld",
                    models.JSONField(
                        blank=True, help_text="JSON-LD schema.org data", null=True
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO",
                "verbose_name_plural": "SEO",
                "ordering": ["slug"],
            },
        ),
        migrations.CreateModel(
            name="Webmaster",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("yandex", "Яндекс.Вебмастер"),
                            ("google", "Google Search Console"),
                        ],
                        default=(
                            ("yandex", "Яндекс.Вебмастер"),
                            ("google", "Google Search Console"),
                        ),
                        max_length=50,
                        unique=True,
                        verbose_name="Вебмастер",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="Для Яндекса текст файла будет совпадать с наименованием файла",
                        max_length=255,
                        verbose_name="Наименование файла без расширения",
                    ),
                ),
                ("text", models.TextField(max_length=1000, verbose_name="Текст файла")),
            ],
            options={
                "verbose_name": "Верификация для вебмастера",
                "verbose_name_plural": "Верификация вебмастеров",
            },
        ),
    ]
