# Generated by Django 4.2.16 on 2026-03-26 06:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="og_type",
            field=models.CharField(
                choices=[
                    (
                        "website",
                        "Website — общая веб-страница (главная, контакты, о салоне)",
                    ),
                    (
                        "product",
                        "Product — товар (подарочный сертификат, косметика для дома, набор ухода)",
                    ),
                    (
                        "service",
                        "Service — услуга салона (стрижка, окрашивание, маникюр, педикюр, косметология, массаж)",
                    ),
                    ("blog", "Blog — блог, полезные статьи, бьюти-советы, тренды"),
                    (
                        "article",
                        "Article — статья или новость (альтернатива для блога)",
                    ),
                    (
                        "profile",
                        "Profile — профиль мастера (стилист, косметолог, бровист)",
                    ),
                    ("place", "Place — место (салон красоты, филиал, студия)"),
                    (
                        "event",
                        "Event — событие (мастер-класс, день красоты, акция, вебинар)",
                    ),
                ],
                default="website",
                help_text="Тип Open Graph: website, article, product...",
                max_length=50,
                verbose_name="OG Тип",
            ),
        ),
    ]
