# Generated by Django 5.1 on 2025-05-17 09:54

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0003_alter_trainer_avatar_alter_trainer_phone_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainer",
            name="phone",
            field=models.CharField(
                max_length=15,
                unique=True,
                validators=[common.validators.validate_russian_phone],
                verbose_name="Телефон",
            ),
        ),
    ]
