# Generated by Django 5.1 on 2025-05-17 13:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0005_trainerreviews_verified"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerimage",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to="trainers.trainer",
                verbose_name="тренер",
            ),
        ),
        migrations.AlterField(
            model_name="trainerrate",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="rates",
                to="trainers.trainer",
                verbose_name="тренер",
            ),
        ),
        migrations.AlterField(
            model_name="trainerreviews",
            name="trainer",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="trainer_reviews",
                to="trainers.trainer",
                verbose_name="тренер",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="rate",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainings",
                to="trainers.trainerrate",
                verbose_name="Тариф",
            ),
        ),
        migrations.AlterField(
            model_name="trainingsession",
            name="trainer",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="trainings",
                to="trainers.trainer",
                verbose_name="Тренер",
            ),
        ),
    ]
