# Generated by Django 5.1 on 2025-06-01 18:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("trainers", "0007_alter_trainerrate_title"),
    ]

    operations = [
        migrations.AlterField(
            model_name="trainerrate",
            name="count_minutes",
            field=models.SmallIntegerField(
                choices=[(45, "45 минут"), (60, "60 минут"), (75, "75 минут")],
                default=60,
                verbose_name="Количество минут",
            ),
        ),
    ]
