# Generated by Django 5.1 on 2025-05-20 22:05

import seo_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seo/",
                validators=[seo_config.models.validate_image_extension],
            ),
        ),
    ]
