# Generated by Django 5.1 on 2025-05-20 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL путь, например: /about/", unique=True
                    ),
                ),
                ("title", models.CharField(blank=True, max_length=255)),
                ("description", models.TextField(blank=True)),
                ("keywords", models.CharField(blank=True, max_length=255)),
                ("og_title", models.CharField(blank=True, max_length=255)),
                ("og_description", models.TextField(blank=True)),
                (
                    "og_image",
                    models.ImageField(blank=True, null=True, upload_to="seo/"),
                ),
            ],
            options={
                "verbose_name": "SEO",
                "verbose_name_plural": "SEO",
            },
        ),
    ]
