# Generated by Django 5.1 on 2025-06-20 12:30

from django.db import migrations, models

import seo_config.models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SEO",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "slug",
                    models.SlugField(
                        help_text="URL путь, например: /about/",
                        unique=True,
                        verbose_name="Слаг",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Заголовок"
                    ),
                ),
                ("description", models.TextField(blank=True, verbose_name="Описание")),
                (
                    "keywords",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Ключевые слова"
                    ),
                ),
                (
                    "og_title",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="OG Заголовок"
                    ),
                ),
                (
                    "og_description",
                    models.TextField(blank=True, verbose_name="OG Описание"),
                ),
                (
                    "og_image",
                    models.ImageField(
                        blank=True,
                        null=True,
                        upload_to="seo/",
                        validators=[seo_config.models.validate_image_extension],
                        verbose_name="OG Изображение",
                    ),
                ),
            ],
            options={
                "verbose_name": "SEO",
                "verbose_name_plural": "SEO",
                "ordering": ["slug"],
            },
        ),
    ]
