# Generated by Django 5.1 on 2025-07-09 07:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="seo",
            name="canonical_url",
            field=models.URLField(
                blank=True,
                help_text="Полный URL для canonical ссылки",
                null=True,
                verbose_name="Canonical URL",
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="changefreq",
            field=models.CharField(
                choices=[
                    ("always", "Всегда"),
                    ("hourly", "Каждый час"),
                    ("daily", "Ежедневно"),
                    ("weekly", "Еженедельно"),
                    ("monthly", "Ежемесячно"),
                    ("yearly", "Ежегодно"),
                    ("never", "Никогда"),
                ],
                default="weekly",
                max_length=10,
                verbose_name="Частота изменений",
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="json_ld",
            field=models.TextField(
                blank=True,
                help_text="Дополнительная структурированная разметка",
                verbose_name="JSON-LD разметка",
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="lastmod",
            field=models.DateTimeField(
                auto_now=True, verbose_name="Дата последнего изменения"
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="nofollow",
            field=models.BooleanField(
                default=False,
                help_text="Запретить переход по ссылкам на странице",
                verbose_name="Nofollow",
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="noindex",
            field=models.BooleanField(
                default=False,
                help_text="Запретить индексацию страницы",
                verbose_name="Noindex",
            ),
        ),
        migrations.AddField(
            model_name="seo",
            name="priority",
            field=models.DecimalField(
                decimal_places=1,
                default=0.5,
                help_text="От 0.1 до 1.0",
                max_digits=2,
                verbose_name="Приоритет в sitemap",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="description",
            field=models.TextField(
                blank=True,
                help_text="Макс. 160 символов",
                verbose_name="Описание (meta description)",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="keywords",
            field=models.CharField(
                blank=True,
                help_text="Через запятую",
                max_length=255,
                verbose_name="Ключевые слова (meta keywords)",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="slug",
            field=models.SlugField(
                help_text="URL путь, например: about/ (без начального и конечного слэша)",
                max_length=255,
                unique=True,
                verbose_name="URL путь",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="title",
            field=models.CharField(
                blank=True,
                help_text="Макс. 60 символов",
                max_length=255,
                verbose_name="Заголовок (title)",
            ),
        ),
    ]
