# Generated by Django 5.1 on 2025-05-20 22:09

import seo_config.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0002_alter_seo_og_image"),
    ]

    operations = [
        migrations.AlterField(
            model_name="seo",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="seo",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ключевые слова"
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="og_description",
            field=models.TextField(blank=True, verbose_name="OG Описание"),
        ),
        migrations.AlterField(
            model_name="seo",
            name="og_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="seo/",
                validators=[seo_config.models.validate_image_extension],
                verbose_name="OG Изображение",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="og_title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="OG Заголовок"
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="slug",
            field=models.SlugField(
                help_text="URL путь, например: /about/",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок"
            ),
        ),
    ]
