# Generated by Django 5.1 on 2025-07-13 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0002_seo_canonical_url_seo_changefreq_seo_json_ld_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="seo",
            name="canonical_url",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="changefreq",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="json_ld",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="lastmod",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="nofollow",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="noindex",
        ),
        migrations.RemoveField(
            model_name="seo",
            name="priority",
        ),
        migrations.AlterField(
            model_name="seo",
            name="description",
            field=models.TextField(blank=True, verbose_name="Описание"),
        ),
        migrations.AlterField(
            model_name="seo",
            name="keywords",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Ключевые слова"
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="slug",
            field=models.SlugField(
                help_text="URL путь, например: /about/",
                unique=True,
                verbose_name="Слаг",
            ),
        ),
        migrations.AlterField(
            model_name="seo",
            name="title",
            field=models.CharField(
                blank=True, max_length=255, verbose_name="Заголовок"
            ),
        ),
    ]
