# Generated by Django 5.1 on 2025-05-21 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("seo_config", "0003_alter_seo_description_alter_seo_keywords_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="seo",
            options={
                "ordering": ["slug"],
                "verbose_name": "SEO",
                "verbose_name_plural": "SEO",
            },
        ),
    ]
