# Generated by Django 5.2.1 on 2025-05-16 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('abonements', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='abonement',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='Описание'),
        ),
    ]
