# Generated by Django 5.1 on 2025-06-01 21:48

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("abonements", "0002_alter_abonement_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="gymvisit",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="gymvisit",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="gymvisit",
            name="id",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, primary_key=True, serialize=False
            ),
        ),
    ]
