# Generated by Django 5.0.6 on 2026-04-13 05:53

import django.db.models.deletion
import django_ckeditor_5.fields
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('categories', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=350, unique=True, verbose_name='Название')),
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('image', models.ImageField(blank=True, null=True, upload_to='services/', verbose_name='Изображение')),
                ('description', models.TextField(blank=True, max_length=5000, null=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Сервис',
                'verbose_name_plural': 'Сервисы',
            },
        ),
        migrations.CreateModel(
            name='Coach',
            fields=[
                ('slug', models.SlugField(blank=True, max_length=255, null=True, unique=True, verbose_name='Слаг')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Полезно для сортировки | чем больше число, тем дальше на странице', verbose_name='Порядковый номер')),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('content', django_ckeditor_5.fields.CKEditor5Field(blank=True, verbose_name='Контент')),
                ('email', models.EmailField(max_length=255, verbose_name='Почта')),
                ('first_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('last_name', models.CharField(max_length=255, verbose_name='Фамилия')),
                ('phone', models.CharField(blank=True, max_length=255, null=True, verbose_name='Телефон')),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='coaches/', verbose_name='Изображение')),
                ('experience', models.PositiveSmallIntegerField(blank=True, help_text='В годах', null=True, verbose_name='Опыт работы')),
                ('categories', models.ManyToManyField(to='categories.category', verbose_name='Категории')),
            ],
            options={
                'verbose_name': 'Тренер',
                'verbose_name_plural': 'Тренеры',
            },
        ),
        migrations.CreateModel(
            name='OrderTraining',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveSmallIntegerField(default=0, help_text='Полезно для сортировки | чем больше число, тем дальше на странице', verbose_name='Порядковый номер')),
                ('is_payed', models.BooleanField(default=False, verbose_name='Оплачен')),
                ('date_start', models.DateField(blank=True, null=True, verbose_name='Дата')),
                ('date_end', models.DateField(blank=True, null=True, verbose_name='Дата окончания')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trainings', to='coaches.coach', verbose_name='Тренер')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trainings', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='order_trainings', to='coaches.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Бронирование тренировки',
                'verbose_name_plural': 'Бронирования тренировок',
            },
        ),
        migrations.CreateModel(
            name='CoachService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price', models.PositiveSmallIntegerField(blank=True, help_text='Цена в рублях от ...', null=True, verbose_name='Цена')),
                ('time', models.PositiveSmallIntegerField(choices=[(45, 45), (60, 60), (75, 75), (90, 90)], help_text='В минутах', verbose_name='Время')),
                ('coach', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='services', to='coaches.coach', verbose_name='Тренер')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='coaches', to='coaches.service', verbose_name='Услуга')),
            ],
            options={
                'verbose_name': 'Услуга тренера',
                'verbose_name_plural': 'Услуги тренеров',
            },
        ),
    ]
