# Generated by Django 5.0.6 on 2026-04-13 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="service",
            options={"verbose_name": "Услуга", "verbose_name_plural": "Услуги"},
        ),
        migrations.AlterField(
            model_name="ordertraining",
            name="date_start",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
    ]
