# Generated by Django 5.0.6 on 2026-04-13 12:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0002_alter_service_options_alter_ordertraining_date_start"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="coach",
            name="slug",
        ),
    ]
