# Generated by Django 5.0.6 on 2026-04-13 12:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0003_remove_coach_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="ordertraining",
            name="order",
        ),
    ]
