# Generated by Django 5.0.6 on 2026-04-14 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0004_remove_ordertraining_order"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertraining",
            name="service",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="order_trainings",
                to="coaches.coachservice",
                verbose_name="Услуга",
            ),
        ),
    ]
