# Generated by Django 5.0.6 on 2026-04-14 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0005_alter_ordertraining_service"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ordertraining",
            name="date_end",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="ordertraining",
            name="date_start",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="Дата начала"
            ),
        ),
    ]
