# Generated by Django 5.0.6 on 2026-04-15 05:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0008_coachreview"),
    ]

    operations = [
        migrations.AddField(
            model_name="coachreview",
            name="is_valid",
            field=models.BooleanField(default=False, verbose_name="Проверен"),
        ),
    ]
