# Generated by Django 5.0.6 on 2026-04-15 05:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0009_coachreview_is_valid"),
    ]

    operations = [
        migrations.RenameField(
            model_name="coachreview",
            old_name="is_valid",
            new_name="is_verified",
        ),
    ]
