# Generated by Django 5.0.6 on 2026-04-19 08:25

import common.mixins
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0010_rename_is_valid_coachreview_is_verified"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Workout",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "date_start",
                    models.DateField(blank=True, null=True, verbose_name="Дата начала"),
                ),
                (
                    "date_end",
                    models.DateField(
                        blank=True, null=True, verbose_name="Дата окончания"
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("personal", "Персональная тренировка"),
                            ("no_trainer", "Тренировка без тренера"),
                        ],
                        default="personal",
                        max_length=20,
                        verbose_name="Тип",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("scheduled", "Запланирована"),
                            ("completed", "Проведена"),
                            ("cancelled", "Отменена"),
                            ("no_show", "Клиент не пришёл"),
                        ],
                        default="scheduled",
                        max_length=20,
                        verbose_name="Статус",
                    ),
                ),
            ],
            options={
                "verbose_name": "Тренировка",
                "verbose_name_plural": "Тренировки",
                "ordering": ["-date_start"],
            },
            bases=(common.mixins.TimeAgoModelMixin, models.Model),
        ),
        migrations.AlterModelOptions(
            name="ordertraining",
            options={
                "ordering": ["-date_start"],
                "verbose_name": "Бронирование тренировки",
                "verbose_name_plural": "Бронирования тренировок",
            },
        ),
        migrations.RenameField(
            model_name="ordertraining",
            old_name="is_payed",
            new_name="is_paid",
        ),
        migrations.AddField(
            model_name="ordertraining",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending_payment", "Ожидает оплаты"),
                    ("paid", "Оплата подтверждена"),
                    ("pending", "Ожидает подтверждения"),
                    ("confirmed", "Подтверждено"),
                    ("cancelled", "Отменено"),
                    ("completed", "Завершено"),
                ],
                default="pending",
                max_length=20,
                verbose_name="Статус",
            ),
        ),
        migrations.AlterField(
            model_name="ordertraining",
            name="date_end",
            field=models.DateField(
                blank=True, null=True, verbose_name="Дата окончания"
            ),
        ),
        migrations.AlterField(
            model_name="ordertraining",
            name="date_start",
            field=models.DateField(blank=True, null=True, verbose_name="Дата начала"),
        ),
        migrations.AddIndex(
            model_name="ordertraining",
            index=models.Index(
                fields=["user", "status"], name="coaches_ord_user_id_5cc789_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="ordertraining",
            index=models.Index(
                fields=["coach", "date_start"], name="coaches_ord_coach_i_6910f5_idx"
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="coach",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="coaches.coach",
                verbose_name="Тренер",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="service",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="workouts",
                to="coaches.coachservice",
                verbose_name="Услуга",
            ),
        ),
        migrations.AddField(
            model_name="workout",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="workouts",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Клиент",
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["user", "date_start"], name="coaches_wor_user_id_44dbc9_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["coach", "date_start"], name="coaches_wor_coach_i_163f22_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="workout",
            index=models.Index(
                fields=["status", "date_start"], name="coaches_wor_status_e543e1_idx"
            ),
        ),
    ]
