# Generated by Django 5.0.6 on 2026-04-21 05:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0011_workout_alter_ordertraining_options_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="CoachSocial",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "social",
                    models.CharField(
                        choices=[
                            ("vk", "VK"),
                            ("tg", "TELEGRAM"),
                            ("max", "MAX"),
                            ("insta", "INSTAGRAM"),
                            ("youtube", "YOUTUBE"),
                        ],
                        max_length=255,
                        verbose_name="Социальная сеть",
                    ),
                ),
                ("link", models.URLField(max_length=255, verbose_name="Ссылка")),
                (
                    "coach",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="socials",
                        to="coaches.coach",
                        verbose_name="Тренер",
                    ),
                ),
            ],
            options={
                "verbose_name": "Социальная сеть тренера",
                "verbose_name_plural": "Социальные сети тренеров",
            },
        ),
    ]
