# Generated by Django 5.0.6 on 2026-04-24 20:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0013_alter_coachreview_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="Exercise",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                (
                    "muscle_group",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("chest", "Грудь"),
                            ("back", "Спина"),
                            ("shoulders", "Плечи"),
                            ("arms", "Руки"),
                            ("legs", "Ноги"),
                            ("abs", "Талия"),
                        ],
                        max_length=50,
                    ),
                ),
                ("description", models.TextField(blank=True)),
            ],
        ),
        migrations.RemoveField(
            model_name="workout",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="workout",
            name="updated_at",
        ),
        migrations.AlterField(
            model_name="workout",
            name="date_end",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Конец"),
        ),
        migrations.AlterField(
            model_name="workout",
            name="date_start",
            field=models.DateTimeField(blank=True, null=True, verbose_name="Начало"),
        ),
        migrations.CreateModel(
            name="ExerciseSet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "order",
                    models.PositiveSmallIntegerField(
                        default=1,
                        verbose_name="Порядковый номер упражнения в тренировке",
                    ),
                ),
                (
                    "set_number",
                    models.PositiveSmallIntegerField(
                        verbose_name="номер подхода (1,2,3...)"
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=6,
                        null=True,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "reps",
                    models.PositiveSmallIntegerField(
                        verbose_name="количество повторений"
                    ),
                ),
                (
                    "rpe",
                    models.PositiveSmallIntegerField(
                        blank=True, null=True, verbose_name="RPE"
                    ),
                ),
                ("completed", models.BooleanField(default=True)),
                (
                    "exercise",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="coaches.exercise",
                        verbose_name="Упражнение",
                    ),
                ),
                (
                    "workout",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="sets",
                        to="coaches.workout",
                        verbose_name="Тренировка",
                    ),
                ),
            ],
            options={
                "ordering": ["workout", "order", "set_number"],
            },
        ),
    ]
