# Generated by Django 5.0.6 on 2026-04-29 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("coaches", "0014_exercise_remove_workout_created_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coachsocial",
            name="social",
            field=models.CharField(
                choices=[
                    ("vk", "VK"),
                    ("tg", "TELEGRAM"),
                    ("max", "MAX"),
                    ("insta", "INSTAGRAM"),
                    ("youtube", "YOUTUBE"),
                    ("whatsapp", "WHATSAPP"),
                ],
                max_length=255,
                verbose_name="Социальная сеть",
            ),
        ),
    ]
