# Generated by Django 5.0.6 on 2026-04-24 08:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="BodyMetricSnapshot",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "recorded_date",
                    models.DateField(
                        help_text="Дата, когда были зафиксированы показатели",
                        verbose_name="Дата замера",
                    ),
                ),
                (
                    "weight_kg",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Вес тела в килограммах (например, 75.50)",
                        max_digits=5,
                        verbose_name="Вес (кг)",
                    ),
                ),
                (
                    "body_fat_percent",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        help_text="Содержание жировой ткани в процентах",
                        max_digits=4,
                        null=True,
                        verbose_name="Процент жира (%)",
                    ),
                ),
                (
                    "muscle_mass_kg",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="Масса скелетных мышц в килограммах",
                        max_digits=5,
                        null=True,
                        verbose_name="Мышечная масса (кг)",
                    ),
                ),
                (
                    "waist_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Обхват талии (см)",
                    ),
                ),
                (
                    "chest_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Обхват груди (см)",
                    ),
                ),
                (
                    "hips_cm",
                    models.DecimalField(
                        blank=True,
                        decimal_places=1,
                        max_digits=5,
                        null=True,
                        verbose_name="Обхват бедер (см)",
                    ),
                ),
                (
                    "source",
                    models.CharField(
                        choices=[
                            ("manual", "Ручной ввод"),
                            ("smart_scale", "Умные весы"),
                            ("trainer", "Запись тренера"),
                        ],
                        default="manual",
                        max_length=20,
                        verbose_name="Источник данных",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True,
                        help_text="Комментарии пользователя или тренера к замеру",
                        verbose_name="Примечания",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="body_metrics",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Снимок прогресса",
                "verbose_name_plural": "История прогресса",
                "ordering": ["-recorded_date"],
                "indexes": [
                    models.Index(
                        fields=["user", "recorded_date"], name="idx_user_date_metrics"
                    )
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="bodymetricsnapshot",
            constraint=models.UniqueConstraint(
                fields=("user", "recorded_date"), name="unique_user_daily_metric"
            ),
        ),
    ]
