# Generated by Django 5.1 on 2025-06-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_user_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="type",
            field=models.CharField(
                choices=[
                    ("client", "Клиент"),
                    ("trainer", "Тренер"),
                    ("admin", "Админ"),
                ],
                default="client",
                max_length=20,
            ),
        ),
    ]
