# Generated by Django 5.0.6 on 2026-04-24 20:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0002_bodymetricsnapshot_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfileQuestionnaire",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Дата создания"
                    ),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="Дата обновления"),
                ),
                (
                    "weight_loss",
                    models.BooleanField(default=False, verbose_name="Цель — похудение"),
                ),
                (
                    "muscle_gain",
                    models.BooleanField(
                        default=False, verbose_name="Хочу нарастить мышечную массу"
                    ),
                ),
                (
                    "cardio",
                    models.BooleanField(
                        default=False, verbose_name="Предпочитаю кардиотренировки"
                    ),
                ),
                (
                    "trainer_help",
                    models.BooleanField(
                        default=False, verbose_name="Нужна помощь тренера"
                    ),
                ),
                (
                    "injuries",
                    models.BooleanField(
                        default=False,
                        verbose_name="Были травмы или ограничения по здоровью",
                    ),
                ),
                (
                    "has_membership",
                    models.BooleanField(
                        default=False, verbose_name="Уже есть абонемент в клуб"
                    ),
                ),
                (
                    "group_lessons",
                    models.BooleanField(
                        default=False, verbose_name="Интересуют групповые занятия"
                    ),
                ),
                (
                    "morning_workouts",
                    models.BooleanField(
                        default=False, verbose_name="Предпочитаю утренние тренировки"
                    ),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="questionnaire",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Пользователь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Анкета пользователя",
                "verbose_name_plural": "Анкеты пользователей",
            },
        ),
    ]
