# Generated by Django 5.0.6 on 2026-04-25 06:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("users", "0003_userprofilequestionnaire"),
    ]

    operations = [
        migrations.DeleteModel(
            name="BodyMetricSnapshot",
        ),
    ]
